[[redirects]]
  from = "/api/auth/*"
  to = "https://qnpvbgczcqegsoehisjr.supabase.co/auth/v1/:splat"
  status = 200
  force = true
  headers = { "apikey" = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucHZiZ2N6Y3FlZ3NvZWhpc2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjE2NjAsImV4cCI6MjA3Nzg5NzY2MH0.FXqLnV-nZk5IT6PXsdWONQvs90-o0cukneaIH3FITlo" }

[[redirects]]
  from = "/api/*"
  to = "https://qnpvbgczcqegsoehisjr.supabase.co/rest/v1/:splat"
  status = 200
  force = true
  headers = { "apikey" = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucHZiZ2N6Y3FlZ3NvZWhpc2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjE2NjAsImV4cCI6MjA3Nzg5NzY2MH0.FXqLnV-nZk5IT6PXsdWONQvs90-o0cukneaIH3FITlo" }
